#syntax=ghcr.io/aica-technology/package-builder:v1.4.0

[metadata]
version = "5.1.0"
description = "Modular ROS 2 extension library for dynamic composition of components and controllers with the AICA robotics framework"

[metadata.collection]
name = "modulo"

[build]
type = "ros"
image = "v2.0.2-jazzy"

[build.dependencies]
"@aica/foss/control-libraries" = "v10.0.0-rc0001"

[build.packages.modulo_components]
source = "./source/modulo_components"

[build.packages.modulo_core]
source = "./source/modulo_core"

[build.packages.modulo_interfaces]
source = "./source/modulo_interfaces"

[build.packages.modulo_utils]
source = "./source/modulo_utils"

[build.packages.modulo_controllers]
source = "./source/modulo_controllers"
