name: Generate and Deploy Documentation

on:
  push:
    branches:
      - main
  release:
    types: [published]
  workflow_dispatch:

jobs:
  deploy:
    name: Generate and Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Generate docs
        uses: mattnotmitt/doxygen-action@v1
        with:
          working-directory: 'doxygen'
          doxyfile-path: 'doxygen.conf'

      - name: Tag version
        shell: bash
        run: |
          TAG="${GITHUB_REF_NAME/\//-}"
          mkdir -p doxygen/docs/versions
          sudo mv doxygen/docs/html doxygen/docs/versions/${TAG}

      - name: Deploy to documentation branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: docs
          publish_dir: ./doxygen/docs
          keep_files: true
